#! /usr/bin/env zsh

DOTFILES="$HOME/.dotfiles"

# ------------------------------------------------
# POWERLEVEL10K INSTANT PROMPT
# ------------------------------------------------
# Enable Powerlevel10k instant prompt. Only initialisation code requiring
# console input should go above this block; everything else should go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi


# ------------------------------------------------
# ZSH
# ------------------------------------------------
HISTFILE="$HOME/.cache/.zsh_history"
HISTSIZE=5000
SAVEHIST=5000

ZLE_RPROMPT_INDENT=0

# Source additional zsh config files
source $DOTFILES/zsh/zsh_aliases

# Enable zsh plugins
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh


# ------------------------------------------------
# HOMEBREW SETTINGS
# ------------------------------------------------
# sets Homebrew to update only once per 24 h
HOMEBREW_AUTO_UPDATE_SECS=$((60 * 60 * 24))


# ------------------------------------------------
# NVM: Node Version Manager
# ------------------------------------------------
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" --no-use
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"


# ------------------------------------------------
# PYENV: Python Version Manager
# ------------------------------------------------
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi


# ------------------------------------------------
# POWERLEVEL10K
# ------------------------------------------------
source /usr/local/opt/powerlevel10k/powerlevel10k.zsh-theme
source $DOTFILES/zsh/p10k
